### ISSUE TITLE
Integrating hydro reservoir capacities

### ISSUE THREAD

**Issue by koen-vg** [pypsa-meets-earth/pypsa-earth#39]
To model hydro powerplants, we need data on:
- The power plants themselves: generation capacities (taken care of by powerplantmatching),
- The hourly inflow for each power plant (see #38), and
- The reservoir capacity for each powerplant (this issue).

Not all hydro power plants have a reservoir (run-of-river plants do not), but those that have reservoirs provide flexibility to the energy system by being able to shift generation in time.

As a starting point, we can investigate using the GRanD database (http://globaldamwatch.org/grand/). The data can be freely used, but note that the license doesn't allow us to redistribute the data. There may also be other suitable databases that we could use.

The main task for this issue is integrating the reservoir data (from e.g. GRanD) with our existing powerplant data (from powerplantmatching), and inflow modelling data (see #38).
- One option is to match by location, and assign reservoirs in GRanD to the closest available powerplant from powerplantmatching.
- Other options could also be consired. Does GRanD include generation capacities? Is its coverare good? If so, we could use it as "the" data for hydro power plants, instead of anything from powerplantmatching.

**Comment by koen-vg** [comment]
Actually, it looks like atlite even can give hydro reservoir data! (Computed from the HydroSHEDS dataset.) This might be a better option for us, and certainly simpler. See also #38.

**Comment by pz-max** [comment]
@MPavicevic maybe you have some comments here?

**Comment by MPavicevic** [comment]
Hey I actually do!

There are 2 ways to approach computation of missing data. 

1.For most dams either nominal head or total dam height is also reported. This is super useful information which i used in my study to compute the total reservoir volume. I also used some geometric simplification such as trapezoidal shape to avoid overestimation of the total storage capacity. If you know the total surface area of the lake in front of the dam (from satellite data, or some other GIS polygons) than its super easy. I was using the width of the river as the bottom edge and width of the lake as top edge of the trapezoidal shape. Computing the storage capacity in MWh is than strait forward once you know the installed power and either the nominal turbine flow rate or the nominal head (usually both can be easily find online)
2. If you dont want to bother with all these computations you can just use some machine learning algorithm that estimates the storage capacity based on the known ones (i found this method to be less good)

If you compare different databases, you will probably spot that some hydro dams are named differently across different sources and in the end you will probably run into the similar issue as i did where instead of 215 you end up with 300+. A lot of attention is needed here. 

I just forwarded my hydro dam database to Max so you can take a look.

Good luck.

**Comment by davide-f** [comment]
#232 integrates the hydro_capacities.csv file needed for modelling reservoirs.
Such file shall be revised, especially for modelling the inflows. Now they are simply a constant value proportional to the total volume of the reservoir, and it must be revised
