### ISSUE TITLE
Need to split Senegal-Gambia data in separate shapefiles. Related to issue #40 

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/pypsa-earth#53]
We download generators, towers, lines, etc. from Geofabrik. 
BY default geofabrik assigns one country shapes for "Senegal-Gambia".
According to the ISO these should be represented be splitted.

We need to do the following:
- Take the country shapefile from @davide-f where SN and GM are separate shapes
- Split SN-GM data into SN and GM respectively. This could work with shapely intersect. Though must be carefully performed. Some edge-cases might be interconnector lines

**Comment by mnm-matin** [comment]
Lines for SN-GM
![image](https://user-images.githubusercontent.com/45293386/128031082-3d91f539-1758-46b6-9a95-383e1efc69fa.png)

Substations for SN-GM
![image](https://user-images.githubusercontent.com/45293386/128031322-1914ba39-ad88-4cf1-a19f-988deca49e19.png)

Due to the sparsity of data, I would highly recommend keeping SN-GM as merged area. Best!

**Comment by pz-max** [comment]
From a long-term perspective, if data becomes more available, splitting SN-GM seems more sustainable.
It would also avoid that we have to merge GDP rasters, GADM shapefiles for SN-GM.
I think we exclude SN-GM for now - until someone wants to split them

**Comment by mnm-matin** [comment]
What do you think about the line circle in red above. How do you propose splitting it? I'm asking because even if more data becomes available it is more likely (in my [opinion](https://www.esi-africa.com/industry-sectors/generation/omvg-interconnection-on-course-to-connect-the-gambia-by-2019/)) that this will be the case for the newly acquired data. 

Also do you think it might be necessary to merge other countries in africa? (for example lesotho and south-africa)

**Comment by pz-max** [comment]
Yes, indeed a challenge with interconnectors. I saw Nigeria also had OSM lines being tagged as "Nigeria" but crossed other countries. So it's a problem we generally face. Maybe PyPSA-Eur handled this special case already.

Regarding its impact on the energy system model, I guess if a line is tagged "SN" or "GM" might have no influence on the optimisation. It might only matter if someone wants to quantify the current value £$€ of assets in a country (there I am sure we can find solutions).

Would keep countries split as far as possible for now. Maybe good to know Lesotho (33km2) is a bit larger than Beligum (30km2), and roughly 7 times smaller than UK (210km2). Belgium is a country which we model in PyPSA-Eur.
