### ISSUE TITLE
naming for the exported csv and geojson is currently hardcode to africa_all but should be based on the countries that are being filtered for.

### ISSUE THREAD

**Issue by mnm-matin** [pypsa-meets-earth/pypsa-earth#69]

**Comment by pz-max** [comment]
A name in terms of a number makes sense to me. I.e. ["NG", "NA"] could result in a name **africa_2** or ["NG", "NA", "ZA"] could result to a name **africa_3**. The number is hence, `len(<list>)`. 

Pro: Name suggest the number of countries included
Con: Might lead to required modifications in the Snakefile and co because of the dynamic name.

Personally the cons overweigh a bit the pro's. Recent changes from Ayman let at least the continent name switch if the data is extracted for another region, see [here](https://github.com/pypsa-meets-africa/pypsa-africa/blob/new-main/scripts/osm_pbf_power_data_extractor.py). Further, the fact that the modeller/analyst always modifies the config.yaml and should be aware of the inputs, I guess having this indicative name is not required.

Please, @mnm-matin close this issue if that is ok with you.

**Comment by davide-f** [comment]
Probably with the new scenario management this issue is obsolete.
I'm closing it but feel free to reopen if you think differently
